import { createHmac, randomUUID } from 'node:crypto';
import type { ComplianceReport, RiskBand } from '../domain/types';
import type { KycRepository } from '../store/repository';
import type { Clock } from '../util/clock';
import { canonicalJson } from '../util/canonical';

/**
 * Compliance reporting (README component 3, reporting half).
 *
 * The report is the artefact a marketplace hands to an auditor or a regulator,
 * so it is built to be provably PII-free: it references sellers by their
 * marketplace-scoped `subjectId`, quotes the salted credential digest and the
 * ledger anchor hash as evidence, and never copies names, dates of birth or
 * document numbers. The signature (HMAC-SHA256 today, ECDSA P-256 when the
 * PDF-signing pipeline lands) lets a counterparty detect later edits.
 */
export interface ReportWindow {
  from?: string;
  to?: string;
}

export class ReportService {
  constructor(
    private readonly repository: KycRepository,
    private readonly clock: Clock,
    private readonly signingKey: string,
    private readonly keyId = 'report-key-1',
  ) {}

  async generate(marketplaceId: string, window: ReportWindow = {}): Promise<ComplianceReport> {
    const to = window.to ? new Date(window.to) : this.clock.now();
    const from = window.from ? new Date(window.from) : new Date(to.getTime() - 30 * 24 * 60 * 60 * 1000);
    if (Number.isNaN(from.getTime()) || Number.isNaN(to.getTime())) {
      throw new Error('report window must be valid ISO timestamps');
    }
    if (from > to) {
      throw new Error('report window "from" must not be after "to"');
    }

    const records = await this.repository.listByMarketplace(marketplaceId, {
      from: from.toISOString(),
      to: to.toISOString(),
    });

    const generatedAt = this.clock.now().toISOString();
    const riskDistribution: Record<RiskBand, number> = { low: 0, medium: 0, high: 0 };
    const driverCounts = new Map<string, { code: string; label: string; occurrences: number }>();
    let verified = 0;
    let review = 0;
    let rejected = 0;
    let sanctionsHits = 0;
    let scoreTotal = 0;

    for (const record of records) {
      riskDistribution[record.risk.band] += 1;
      scoreTotal += record.risk.score;
      sanctionsHits += record.risk.sanctionsHits.length;
      if (record.status === 'verified') verified += 1;
      if (record.status === 'review') review += 1;
      if (record.status === 'rejected') rejected += 1;

      for (const item of record.risk.features) {
        const existing = driverCounts.get(item.code);
        if (existing) existing.occurrences += 1;
        else driverCounts.set(item.code, { code: item.code, label: item.label, occurrences: 1 });
      }
    }

    const blockedListings = await this.repository.countListingDecisions(marketplaceId, true);

    const unsigned = {
      reportId: 'rpt_' + randomUUID().replace(/-/g, '').slice(0, 20),
      generatedAt,
      window: { from: from.toISOString(), to: to.toISOString() },
      marketplaceId,
      totals: {
        submissions: records.length,
        verified,
        review,
        rejected,
        blockedListings,
        sanctionsHits,
        averageRiskScore: records.length === 0 ? 0 : Math.round(scoreTotal / records.length),
      },
      riskDistribution,
      topRiskDrivers: [...driverCounts.values()]
        .sort((left, right) => right.occurrences - left.occurrences || left.code.localeCompare(right.code))
        .slice(0, 10),
      records: records.map((record) => ({
        submissionId: record.submissionId,
        subjectId: record.subjectId,
        status: record.status,
        riskScore: record.risk.score,
        riskBand: record.risk.band,
        credentialDigest: record.credentialDigest,
        ledgerHash: record.ledgerAnchorHash,
        decidedAt: record.evaluatedAt,
      })),
      attestation:
        'Generated by NFT-KYC Hub. Contains no personal data: sellers are referenced by ' +
        'marketplace-scoped subject ids and evidence is quoted as salted credential digests ' +
        'and ledger anchor hashes.',
    };

    return {
      ...unsigned,
      signature: {
        alg: 'HMAC-SHA256',
        keyId: this.keyId,
        value: createHmac('sha256', this.signingKey).update(canonicalJson(unsigned), 'utf8').digest('hex'),
      },
    };
  }
}

/** Verifies a report's signature — used by counterparties and by the report tests. */
export function verifyReportSignature(report: ComplianceReport, signingKey: string): boolean {
  const { signature, ...unsigned } = report;
  const expected = createHmac('sha256', signingKey).update(canonicalJson(unsigned), 'utf8').digest('hex');
  return expected === signature.value;
}